name: webdav
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.1.0

dependencies: 
  http: ^1.1.0
  oauth2: ^2.0.0
  shelf: ^1.2.0
  xml: ^5.3.1

dev_dependencies:
  very_good_analysis: ^5.1.0
  # pass
